### ISSUE TITLE
Timer01 example in QEUM(A57+virt)

### ISSUE THREAD

**Issue by NienfengYao** [eggman/raspberrypi#1]
Hi eggman, 

I am appreciate your project, it's good tutorial for bare-metal exercise. I am studying your ex: timer01. It works fine on QEMU(A53+raspi3), I am trying do this on QEMU(A57+virt). But until now, it doesn't work, can you give me some suggestion? My code is [here](https://github.com/NienfengYao/armv8-bare-metal). Current status is that I can see the CNTV_CTL_EL0:bit2(ISTATUS) changes but the irq_interrupt handle call back function doesn't be called, and we also don't observe any changes in ISR_EL1(there is no IRQ interrupt pending detected). Did I miss something or suggest me what to check. Thank you.

```
make run
...
Hello world!
timer_test
CurrentEL = 0x00000000 00000004    /* EL1 */
DAIF = 0x00000000 000003C0         /* DAIF bits are set */
CNTV_CTL_EL0 = 0x00000000 00000000
Disable the timer, CNTV_CTL_EL0 = 0x00000000 00000000 /* Clear bits of ENABLE/IMASK */
CNTFRQ_EL0 = 0x00000000 03B9ACA0   /* frequency of the system counter = 62.5MHz */ 
CNTVCT_EL0 = 0x00000000 000242C5   /* current 64-bit virtual count value */
Set it as next 1 sec, CNTV_CVAL_EL0 = 0x00000000 03BBEF65 /* set compare value */
Enable the timer, CNTV_CTL_EL0 = 0x00000000 00000001  /* Set bit ENABLE */
Enable IRQ, DAIF = 0x00000000 00000340  /* Clear IRQ mask bit */

/* we observe the CNTVCT_EL0 and CNTV_CTL_EL0 */
/* if time up, CNTV_CTL_EL0[2] = 1 */
CNTVCT_EL0 = 0x00000000 000390CA, CNTV_CTL_EL0 = 0x00000000 00000001
CNTVCT_EL0 = 0x00000000 0003D41F, CNTV_CTL_EL0 = 0x00000000 00000001
...
/* time up, CNTV_CTL_EL0[2]: ISTATUS = 1*/
CNTVCT_EL0 = 0x00000000 03BCE5C4, CNTV_CTL_EL0 = 0x00000000 00000005
SPSR_EL1 = 0x00000000 00000000
ISR_EL1 = 0x00000000 00000000
/* But the irq_handler doesn't be called and ISR_EL1[7] = 0 */
/* there is no IRQ interrupt pending detected */

QEMU: Terminated
```

**Comment by eggman** [comment]
Hello NienfengYao 

I saw your code.
I think your code is no interrupt signal routing.
Generic timer asserted an interrupt , but the interrupt signal has no route to ARM core.

Suggestion
- check GIC spec.
- check GIC codes on Github.
 https://github.com/takeharukato/sample-tsk-sw/blob/master/hal/aarch64/gic-pl390.c
 https://github.com/xhd2015/rsp3-armv8-baremetal/blob/master/src/arch/qemu_virt/main_demo_TimerInterrupt.cpp
- check GIC base address and interrupt number in QEMU source code.

best regards

**Comment by NienfengYao** [comment]
Hi, eggman.
Thanks for your suggestion, I am studying it.

best regards

**Comment by eggman** [comment]
Timer IRQ works.  
https://github.com/NienfengYao/armv8-bare-metal/commit/7aaa433576602b93d426f63b1a8a9fe473a52506
